import 'phaser';

export class LevelData {

    level0 = [
        'wyyyyyyyyyyyyyyyyyyz',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x        44        v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v'
    ];

    level00 = [
        'wyyyyyyyyyyyyyyyyyyz',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x        22        v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v'
    ];


    level1 = [
        'wyyyyyyyyyyyyyyyyyyz',
        'x                  v',
        'x                  v',
        'x111111111111111111v',
        'x111111111111111111v',
        'x222222222222222222v',
        'x222222222222222222v',
        'x333333333333333333v',
        'x333333333333333333v',
        'x444444444444444444v',
        'x444444444444444444v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v',
        'x                  v'
    ];
    
    level2 = [
        'xxxxxxxxxxxxxxxxxxxx',
        'x                  x',
        'x    oooooooooo    x',
        'x   oooooooooooo   x',
        'x   oooooooooooo   x',
        'x   oo  oooo  oo   x',
        'x   oo  oooo  oo   x',
        'x   oooooooooooo   x',
        'x     oooooooo     x',
        'x     oooooooo     x',
        'x      oooooo      x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x'
    ];

    level3 = [
        'xxxxxxxxxxxxxxxxxxxx',
        'x                  x',
        'x                  x',
        'x     O      o     x',
        'x      o    o      x',
        'x     oooooooo     x',
        'x    oo  oo  oo    x',
        'x   oooooooooooo   x',
        'x   o oooooooo o   x',
        'x   o o      o o   x',
        'x      oo  oo      x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x'
    ];

    level4 = [
        'xxxxxxxxxxxxxxxxxxxx',
        'x                  x',
        'x       ooooo      x',
        'x     ooooooooo    x',
        'x    ooooooooooo   x',
        'x    ooooooooooo   x',
        'x   oooooooooo     x',
        'x   ooooooo        x',
        'x   oooo           x',
        'x   ooooooo        x',
        'x   oooooooooo     x',
        'x    ooooooooooo   x',
        'x    ooooooooooo   x',
        'x     ooooooooo    x',
        'x       ooooo      x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x',
        'x                  x'
    ];

    levels = [
        this.level1,
        this.level2,
        this.level3,
        this.level4
    ];
}